### ISSUE TITLE
W3C Validation errors for Retina Images code

### ISSUE THREAD

**Issue by BattyBlogger** [Retina-Images/Retina-Images#33]
Hi Jeremy, I'm using your Retina Images code to serve high-res images on 
my site to devices that can take advantage of them. It works great, and 
I'm on the latest 1.61 code. I'd really like my pages to pass the HTML 
validation on this page: http://validator.w3.org/ , but there are two 
errors that are coming from your code that I can't get rid of. The first 
one seems possibly bogus due to the leading "-" characters, was that a 
legacy thing? The second one I don't know.

These errors appear even when I run your page through the validator, so 
I'm sure it's nothing specific to my site.

Any ideas?

Try to validate this, which has the Retina Images code:
http://retina-images.complexcompulsions.com/

 1. Error/Line 40, Column 243/:Bad value only screen and
    (-moz-min-device-pixel-ratio: 2), only screen and
    (-o-min-device-pixel-ratio: 2/1), only screen and
    (-webkit-min-device-pixel-ratio: 2), only screen and
    (min-device-pixel-ratio: 2) for attribute media on element style:
    Expected a letter at start of a media feature part but saw - instead.

2. Error/Line 40, Column 243/:Element style is missing required
    attribute scoped.

    |...creen and (min-device-pixel-ratio: 2)"*>*#devicePixelRatio{background-image:url(...|

**Comment by jeremyworboys** [comment]
@BattyBlogger The first error is due to vendor prefixing. This is required to support some older (possibly still current, I'm not certain at this moment) browsers.

The second is a recent addition to the validator. It suggests that the `<style>` tag should have a `scope` attribute or be in the document `<head>`. The `<style>` tag can not be in the `<head>` as it must be in the `<noscript>` to prevent an additional, unnecessary HTTP request when the Javascript runs. The `<noscript>` tag is not valid in the document `<head>`. I have not tested adding the `scope` attribute to the style tag, but I assume it will not work as currently implemented as the CSS targets the `<html>` element which would be excluded by the scoping. You would need to add a `<div>` with a unique `id` and target it with the CSS selector.
